version: "3.9"

services:
  mongo_db:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"


  test_copy:
    build: .
    container_name: task_copy
    depends_on:
      - mongo_db







